Citizen.CreateThread(function()
    -- AddTextEntry("that code", "name")
    AddTextEntry("dv4r", "Ducati V4")
    AddTextEntry("az22", "Hyundai Azera")
    AddTextEntry("santafe", "Hyundai Santa")
    AddTextEntry("sonata20", "Hyundai Sonata")
    AddTextEntry("jeep2012", "Jeep Wangler")
    AddTextEntry("nh2r", "H2R")
    AddTextEntry("rc", "KTM RC 390")
    AddTextEntry("xuv700bygsm", "XUV 700")
    AddTextEntry("hayabusa", "Hayabusa")
    AddTextEntry("suzukigv", "Vitara")
    AddTextEntry("paksuzuki", "WagonR")
    AddTextEntry("teslapd", "Tesla Model S")
    AddTextEntry("fortuner", "Fortuner")
end)